#!/usr/bin/env bash
# Run Apache on holbertonschool/265-0 container

# Add ServerName to the Apache configuration
echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Start the Apache service
service apache2 start

if pgrep -x "apache2" > /dev/null
then
    echo "apache2 is running"
else
    echo "Failed to start apache2"
    exit 1
fi
